apiVersion: v1
kind: PersistentVolume
metadata:
    name: gp2
    labels:
        type: local
spec: 
    storageClassName: gp2
    capacity:
        storage: 5Gi
    accessModes:
            - ReadWriteOnce
    hostPath:
        path: "/home/test/Near-RT-RIC-test/rountingDB/rountingDBdata"
        
