apiVersion: v1
kind: PersistentVolume
metadata:
    name: gp2
    labels:
        type: local
spec: 
    storageClassName: gp2
    capacity:
        storage: 5Gi
    accessModes:
            - ReadWriteOnce
    hostPath:
        path: "/home/lienlab305/work/III/Near-RT\ RIC\ and\ WBT/RIC\ component/rountingDB/rountingDBdata"
        
